#!/bin/sh

# install dependencies
[ -r PKGBUILD ] && {
  source "$(pwd)/PKGBUILD"
  yay --sync --noconfirm --noprogressbar --quiet --needed "${depends[@]}" "${makedepends[@]}"
}

# add trusted keys to keychain
if [ -r "trusted-keys" ]; then
  grep -v '^ *#' < trusted-keys | while IFS= read -r key; do
    gpg --recv-key "$key"
  done
fi

exec makepkg --syncdeps --clean --cleanbuild --nocolor --noconfirm --needed --noprogressbar "$@"